name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
    - uses: wei/curl@v1
      with:
        args: https://l3p3.de/svr/site-update.txt?site=Hoffsite
